/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as ApprootImport } from './pages/app/__root'
import { Route as IndexImport } from './pages/index'
import { Route as AppIndexImport } from './pages/app/index'
import { Route as AppProtectedImport } from './pages/app/_protected'
import { Route as AppAuthSignUpImport } from './pages/app/auth/sign-up'
import { Route as AppAuthSignInImport } from './pages/app/auth/sign-in'
import { Route as AppAuthResetPasswordImport } from './pages/app/auth/reset-password'
import { Route as AppAuthForgotPasswordImport } from './pages/app/auth/forgot-password'
import { Route as AppProtectedDashboardImport } from './pages/app/_protected/dashboard'

// Create Virtual Routes

const AppImport = createFileRoute('/app')()

// Create/Update Routes

const ApprootRoute = ApprootImport.update({
  id: '/__root',
  getParentRoute: () => AppRoute,
} as any)

const AppRoute = AppImport.update({
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppProtectedRoute = AppProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthSignUpRoute = AppAuthSignUpImport.update({
  path: '/auth/sign-up',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthSignInRoute = AppAuthSignInImport.update({
  path: '/auth/sign-in',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthResetPasswordRoute = AppAuthResetPasswordImport.update({
  path: '/auth/reset-password',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthForgotPasswordRoute = AppAuthForgotPasswordImport.update({
  path: '/auth/forgot-password',
  getParentRoute: () => AppRoute,
} as any)

const AppProtectedDashboardRoute = AppProtectedDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AppProtectedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/app/__root': {
      preLoaderRoute: typeof ApprootImport
      parentRoute: typeof AppRoute
    }
    '/app/_protected': {
      preLoaderRoute: typeof AppProtectedImport
      parentRoute: typeof AppImport
    }
    '/app/': {
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/app/_protected/dashboard': {
      preLoaderRoute: typeof AppProtectedDashboardImport
      parentRoute: typeof AppProtectedImport
    }
    '/app/auth/forgot-password': {
      preLoaderRoute: typeof AppAuthForgotPasswordImport
      parentRoute: typeof AppImport
    }
    '/app/auth/reset-password': {
      preLoaderRoute: typeof AppAuthResetPasswordImport
      parentRoute: typeof AppImport
    }
    '/app/auth/sign-in': {
      preLoaderRoute: typeof AppAuthSignInImport
      parentRoute: typeof AppImport
    }
    '/app/auth/sign-up': {
      preLoaderRoute: typeof AppAuthSignUpImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AppRoute.addChildren([
    AppProtectedRoute.addChildren([AppProtectedDashboardRoute]),
    AppIndexRoute,
    AppAuthForgotPasswordRoute,
    AppAuthResetPasswordRoute,
    AppAuthSignInRoute,
    AppAuthSignUpRoute,
  ]),
])

/* prettier-ignore-end */
