/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as ProtectedImport } from './pages/_protected'
import { Route as IndexImport } from './pages/index'
import { Route as AppAuthSignUpImport } from './pages/app/auth/sign-up'
import { Route as AppAuthSignInImport } from './pages/app/auth/sign-in'
import { Route as AppAuthResetPasswordImport } from './pages/app/auth/reset-password'
import { Route as AppAuthForgotPasswordImport } from './pages/app/auth/forgot-password'
import { Route as ProtectedAppDashboardImport } from './pages/_protected/app/dashboard'

// Create/Update Routes

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppAuthSignUpRoute = AppAuthSignUpImport.update({
  path: '/app/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AppAuthSignInRoute = AppAuthSignInImport.update({
  path: '/app/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AppAuthResetPasswordRoute = AppAuthResetPasswordImport.update({
  path: '/app/auth/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const AppAuthForgotPasswordRoute = AppAuthForgotPasswordImport.update({
  path: '/app/auth/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedAppDashboardRoute = ProtectedAppDashboardImport.update({
  path: '/app/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/_protected/app/dashboard': {
      preLoaderRoute: typeof ProtectedAppDashboardImport
      parentRoute: typeof ProtectedImport
    }
    '/app/auth/forgot-password': {
      preLoaderRoute: typeof AppAuthForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/app/auth/reset-password': {
      preLoaderRoute: typeof AppAuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/app/auth/sign-in': {
      preLoaderRoute: typeof AppAuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/app/auth/sign-up': {
      preLoaderRoute: typeof AppAuthSignUpImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ProtectedRoute.addChildren([ProtectedAppDashboardRoute]),
  AppAuthForgotPasswordRoute,
  AppAuthResetPasswordRoute,
  AppAuthSignInRoute,
  AppAuthSignUpRoute,
])

/* prettier-ignore-end */
