name: Deploy Production Frontend

on:
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          cd client
          pnpm install

      - name: Build project
        run: |
          cd client
          pnpm run build

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Add SSH Key to SSH Agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key

      - name: Deploy frontend
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: 'client/build/'  # or the build output directory for your frontend
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '/var/www/lnkc/client'  # Change this to your target directory on the server
        with:
          ssh-private-key: ~/.ssh/deploy_key